backend:
  name: git-gateway
  branch: main
media_folder: public/img
media_library:
  name: uploadcare
  config:
    publicKey: "ffbaed068f811fb8f504"
  settings:
    autoFilename: true
    defaultOperations: "/resize/900x400/"
locale: es
slug:
  encoding: "ascii"
  clean_accents: true
  sanitize_replacement: "_"
collections:
  - name: "meta"
    label: "Meta"
    delete: false
    editor:
      preview: false
    files:
      - name: "tags"
        label: "Tags"
        file: "meta/tags.yml"
        description: "List of tags"
        fields:
          - name: tags
            label: Tags
            label_singular: "Tag"
            widget: list
            fields:
              - label: "Slug"
                name: "slug"
                widget: "string"
                hint: "Identificación del tag usar solo una palabra."
              - label: "Nombre visual"
                name: "name"
                widget: "string"
                hint: "Nombre del tag, esto será visible."
  - label: "Blog"
    name: "blog"
    folder: "content/blogPosts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}_{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string", required: true }
      - { label: "Header", name: "header", widget: "string", required: true }
      - {
          label: Tags,
          label_singular: "Tag",
          name: "tags",
          widget: list,
          summary: "{{fields.tag}}",
          required: true,
          field:
            {
              label: Tag,
              name: tag,
              widget: relation,
              collection: "meta",
              file: "tags",
              search_fields: ["tags.*.name"],
              display_fields: ["tags.*.name"],
              value_field: "tags.*.slug",
            },
        }
      - {
          label: "Publish Date",
          name: "date",
          widget: "datetime",
          required: true,
        }
      - {
          label: "Featured Image",
          name: "thumbnail",
          widget: "image",
          required: false,
        }
      - { label: "Body", name: "body", widget: "markdown", required: true }
