import { GetStaticProps } from "next";
import Head from "next/head";
import Link from "next/link";
import Image from "next/image";
import { TagIcon } from "../components/icons";
import { Post } from "../interfaces/post.interface";
import { Tag } from "../interfaces/tag.interface";
import { getRecentPosts } from "../lib/utils/posts";
import { getAllTags } from "../lib/utils/tags";
import Styles from "../styles/modules/Home.module.scss";

export default function Home({ posts, tags }: { posts: Post[]; tags: Tag[] }) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={Styles.home}>
        <div className={Styles["home-content"]}>
          <h1 className={Styles["home-content_title"]}>
            Publicaciones más recientes
          </h1>
          <div className={Styles["home-content_list"]}>
            {posts.map((post) => (
              <div className={Styles.post} key={post.slug}>
                <div className={Styles["post-img"]}>
                  <Link href={"/posts/" + post.slug}>
                    <a>
                      <Image
                        src={
                          post.thumbnail
                            ? post.thumbnail
                            : "/img/defaultPost.png"
                        }
                        alt={post.title}
                        width={900}
                        height={400}
                        layout="responsive"
                      ></Image>
                    </a>
                  </Link>
                </div>
                <div className={Styles["post-body"]}>
                  <div className={Styles["post-tags"]}>
                    {post.tag.map((tag) => (
                      <span key={tag}>{tag}</span>
                    ))}
                  </div>
                  <Link href={"/posts/" + post.slug}>
                    <a className={Styles["post-title"]}>{post.title}</a>
                  </Link>
                  <p>{post.header}</p>
                  <span>{post.date}</span>
                </div>
              </div>
            ))}
          </div>
        </div>
        <div className={Styles["home-tags"]}>
          <h4 className={Styles["home-tags_title"]}>
            <TagIcon color={"white"}></TagIcon>
            TAGS
          </h4>
          <ul className={Styles["home-tags_list"]}>
            {tags.map((tag, index) => (
              <li key={`${index}-${tag.slug}`}>
                <Link href={`/tags/${tag.slug}`}>
                  <a className="btn btn-primary btn-tag">{tag.name}</a>
                </Link>
              </li>
            ))}
          </ul>
        </div>
      </div>
    </>
  );
}

export const getStaticProps: GetStaticProps = async () => {
  const tags = getAllTags();
  const posts = getRecentPosts();
  console.log(posts);

  return {
    props: {
      posts,
      tags,
    },
  };
};
