import { GetStaticProps } from "next";
import Head from "next/head";
import Link from "next/link";
import { TagIcon } from "../components/icons";
import { Tag } from "../interfaces/tag.interface";
import { getAllTags } from "../lib/utils/tags";
import Styles from "../styles/modules/Home.module.scss";

export default function Home({ tags }: { tags: Tag[] }) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={Styles.home}>
        <div className={Styles["home-content"]}>
          <h1>Publicaciones más recientes</h1>
        </div>
        <div className={Styles["home-tags"]}>
          <h4 className={Styles["home-tags_title"]}>
            <TagIcon color={"white"}></TagIcon>
            TAGS
          </h4>
          <ul className={Styles["home-tags_list"]}>
            {tags.map((tag, index) => (
              <li key={`${index}-${tag.slug}`}>
                <Link href={`/tags/${tag.slug}`}>
                  <a className="btn btn-primary btn-tag">{tag.name}</a>
                </Link>
              </li>
            ))}
          </ul>
        </div>
      </div>
    </>
  );
}

export const getStaticProps: GetStaticProps = async () => {
  const tags = getAllTags();
  const posts: [] = [];
  return {
    props: {
      posts,
      tags,
    },
  };
};
